### ISSUE TITLE
Fx "Always ask where you want to save files" dialog not being honored

### ISSUE THREAD

**Issue by gbcox** [baptistecdr/aria2-integration#298]
I have a download directory specified in Fx, but also have checked "Always ask where you want to save files" checked.  When I save a file, the dialog appears properly, but if I change the destination directory, aria2-integration ignores that choice and will always download to the hardcoded directory rather than honor what is specified in the override dialog.

**Comment by baptistecdr** [comment]
You can choose the filename in the dialog and it will be used when downloading with Aria2 but you can't choose the folder.

Choosing a specifc location will only work locally, because if you have your Aria2 instance on a Linux server and you are 
using the extension on Windows, they won't have the same file system structure.

I can probably add a checkbox in the settings like "Use complete file path when usign Save Link As..."

**Comment by gbcox** [comment]
Ah, I understand.  Yes, it would be a good idea to figure out someway to allow people who are using a local instance to preserve the folder choice.  Whether it be by a checkbox, or doing a check to see if the server is local.  Thanks for the quick response.

**Comment by baptistecdr** [comment]
Alright, I started the development of the feature, I hope to release this, this week. Stay tuned!

**Comment by baptistecdr** [comment]
Hello @gbcox,

I finished the development of your feature request. Could you also test it on your side?
You can find the pre-build version here: https://github.com/baptistecdr/aria2-integration/actions/runs/6678371845 and import the zip file in `about:debugging#/runtime/this-firefox`.

Looking forward for your test,
baptistecdr

**Comment by gbcox** [comment]
Hi, Thanks for the quick response.  Much appreciated.  Unfortunately, it doesn't seem to work.  I checked the box to use the full path, but still downloading to the default folder.

**Comment by gbcox** [comment]
I tried again, but this time deleted the production version I had installed.  Looks like that one was being used instead of the temporary version.  Appears to be working!  Thanks much!

**Comment by baptistecdr** [comment]
Awesome that it works, I got scared for  a few minutes. :D

You won't be able to load permantly my extension because I don't sign the development build, Firefox will reject the installation when installing through about:addons > Install from a file.

I will release the new version tomorrows or Monday

**Comment by gbcox** [comment]
Great, thanks again for the quick response.  I'll keep an eye out for the production version.

**Comment by baptistecdr** [comment]
4.6.0 is available on AMO.
